USE jimmys_tapas_bar;

-- 4. Tapas Vegetarian
INSERT INTO menu_items (id, name, description, detailed_description, price, category, allergens, ingredients, vegan, vegetarian, glutenfree, order_index, is_active) VALUES
('tv001', 'Gebratenes Gemüse der Saison', 'Vegan', 'Frisches saisonales Gemüse, gegrillt mit Olivenöl, Knoblauch und mediterranen Kräutern.', '6,90', 'Vegetarisch', '', 'Saisonales Gemüse, Olivenöl, Knoblauch, Kräuter, Salz, Pfeffer', true, true, true, 1, true),
('tv002', 'Papas Bravas', 'Vegan', 'Knusprig gebratene Kartoffelwürfel mit hausgemachter scharfer Bravas-Sauce aus Tomaten und Paprika.', '6,90', 'Vegetarisch', '', 'Kartoffeln, Tomaten, Paprika, Knoblauch, Olivenöl, Gewürze', true, true, true, 2, true),
('tv003', 'Tortilla de Patata con Aioli', 'Spanisches Kartoffel-Omelett', 'Traditionelle spanische Tortilla aus Kartoffeln und Eiern, serviert mit hausgemachter Aioli.', '6,90', 'Vegetarisch', 'Eier', 'Kartoffeln, Eier, Zwiebeln, Olivenöl, Aioli', false, true, true, 3, true),
('tv004', 'Pimientos de Padrón', 'Vegan', 'Kleine grüne Paprika aus Galicien, gegrillt mit grobem Meersalz und Olivenöl. Russisches Roulette der Schärfe!', '6,90', 'Vegetarisch', '', 'Pimientos de Padrón, Olivenöl, Meersalz', true, true, true, 4, true),
('tv005', 'Kanarische Kartoffeln im Salzmantel', 'Vegan', 'Kleine Kartoffeln gekocht im Salzmantel nach kanarischer Art, serviert mit Mojo-Sauce.', '6,90', 'Vegetarisch', '', 'Kleine Kartoffeln, Meersalz, Mojo-Sauce, Petersilie, Knoblauch', true, true, true, 5, true),
('tv006', 'Fetakäse Häppchen', 'Gebratener Feta', 'In Olivenöl gebratene Feta-Würfel mit Honig, Thymian und gerösteten Pinienkernen.', '6,90', 'Vegetarisch', 'Milch, Schalenfrüchte', 'Feta-Käse, Honig, Thymian, Pinienkerne, Olivenöl', false, true, true, 6, true),
('tv007', 'Rosmarin Ziegenkäse', 'Gebackener Ziegenkäse', 'Warmer Ziegenkäse mit frischem Rosmarin, Honig und gerösteten Walnüssen.', '6,90', 'Vegetarisch', 'Milch, Schalenfrüchte', 'Ziegenkäse, Rosmarin, Honig, Walnüsse', false, true, true, 7, true),
('tv008', 'Falafel', 'Orientalische Kichererbsenbällchen', 'Hausgemachte Falafel aus Kichererbsen und orientalischen Gewürzen, serviert mit Tahini-Sauce.', '6,90', 'Vegetarisch', 'Sesam', 'Kichererbsen, Petersilie, Koriander, Knoblauch, Kreuzkümmel, Tahini', true, true, true, 8, true),
('tv009', 'Feta Käse überbacken Cherry', 'Überbackener Feta mit Cherry-Tomaten', 'Im Ofen überbackener Feta mit Cherry-Tomaten, Oregano und Olivenöl.', '6,90', 'Vegetarisch', 'Milch', 'Feta-Käse, Cherry-Tomaten, Oregano, Olivenöl, Zwiebeln', false, true, true, 9, true),
('tv010', 'Überbackene Champignons', 'Mit Käse gratiniert', 'Große Champignons gefüllt mit Kräutern und Käse, im Ofen überbacken.', '6,90', 'Vegetarisch', 'Milch', 'Champignons, Käse, Petersilie, Knoblauch, Semmelbrösel', false, true, false, 10, true),
('tv011', 'Überbackene Tomaten', 'Gefüllte Tomaten', 'Große Tomaten gefüllt mit Kräutern, Knoblauch und Käse, im Ofen überbacken.', '6,90', 'Vegetarisch', 'Milch', 'Tomaten, Käse, Basilikum, Knoblauch, Semmelbrösel', false, true, false, 11, true),
('tv012', 'Frittierte Auberginen mit Honig', 'Süß-salzige Kombination', 'In Olivenöl frittierte Auberginenscheiben, beträufelt mit spanischem Honig.', '6,90', 'Vegetarisch', '', 'Auberginen, Olivenöl, Honig, Salz', true, true, true, 12, true),
('tv013', 'Champignons al Ajillo', 'Vegan', 'In Knoblauch und Olivenöl gebratene Champignons mit Petersilie und Chili.', '6,90', 'Vegetarisch', '', 'Champignons, Knoblauch, Olivenöl, Petersilie, Chili', true, true, true, 13, true),
('tv014', 'Teigröllchen mit Spinat', 'Blätterteig-Röllchen', 'Knusprige Blätterteig-Röllchen gefüllt mit Spinat, Feta und Pinienkernen.', '6,90', 'Vegetarisch', 'Glutenhaltiges Getreide, Milch, Schalenfrüchte', 'Blätterteig, Spinat, Feta, Pinienkerne, Zwiebeln', false, true, false, 14, true),
('tv015', 'Feta Feigen', 'Süß-salzige Kombination', 'Frische Feigen mit cremigem Feta, Honig und gerösteten Pistazien.', '6,90', 'Vegetarisch', 'Milch, Schalenfrüchte', 'Feigen, Feta-Käse, Honig, Pistazien', false, true, true, 15, true),
('tv016', 'Ziegenkäse überbacken', 'Warmer Ziegenkäse', 'Überbackener Ziegenkäse mit Honig, Thymian und karamellisierten Zwiebeln.', '6,90', 'Vegetarisch', 'Milch', 'Ziegenkäse, Honig, Thymian, Zwiebeln', false, true, true, 16, true),
('tv017', 'Gebratener Spinat mit Cherry Tomaten', 'Vegan', 'Frischer Spinat gebraten mit Cherry-Tomaten, Knoblauch und Olivenöl.', '6,90', 'Vegetarisch', '', 'Spinat, Cherry-Tomaten, Knoblauch, Olivenöl, Pinienkerne', true, true, true, 17, true),

-- 5. Tapas de Pollo
('tp001', 'Hähnchen Filet mit Limetten Sauce', 'Zarte Hähnchenfilets', 'Gegrillte Hähnchenfilets in einer frischen Limetten-Koriander-Sauce mit einem Hauch Chili.', '7,20', 'Hähnchen', '', 'Hähnchenfilet, Limetten, Koriander, Chili, Olivenöl, Knoblauch', false, false, true, 1, true),
('tp002', 'Knusprige Hähnchen Tapas mit Honig-Senf Sauce', 'Panierte Hähnchenstücke', 'Knusprig panierte Hähnchenstücke mit süßer Honig-Senf-Sauce und Sesam.', '7,20', 'Hähnchen', 'Glutenhaltiges Getreide, Sesam', 'Hähnchenfilet, Paniermehl, Honig, Senf, Sesam, Eier', false, false, false, 2, true),
('tp003', 'Hähnchen Spieß mit scharfer Sauce', 'Gegrillter Hähnchenspieß', 'Marinierte Hähnchenstücke am Spieß gegrillt, serviert mit scharfer Chili-Knoblauch-Sauce.', '7,20', 'Hähnchen', '', 'Hähnchenfilet, Chili, Knoblauch, Paprika, Olivenöl, Gewürze', false, false, true, 3, true),
('tp004', 'Hähnchen Filet mit Curry Sauce', 'Exotisches Hähnchen', 'Gebratene Hähnchenfilets in cremiger Curry-Kokosnuss-Sauce mit Ingwer.', '7,20', 'Hähnchen', '', 'Hähnchenfilet, Curry, Kokosmilch, Ingwer, Zwiebeln, Knoblauch', false, false, true, 4, true),
('tp005', 'Hähnchen Filet mit Mandel Sauce', 'Hähnchen in Mandelsauce', 'Zarte Hähnchenfilets in cremiger Mandel-Sahne-Sauce mit einem Hauch Sherry.', '7,20', 'Hähnchen', 'Milch, Schalenfrüchte', 'Hähnchenfilet, Mandeln, Sahne, Sherry, Zwiebeln', false, false, true, 5, true),
('tp006', 'Gegrillter Hähnchen-Chorizo-Spieß', 'Spanische Kombination', 'Abwechselnd gespießte Hähnchen- und Chorizo-Stücke vom Grill mit Paprika.', '7,20', 'Hähnchen', '', 'Hähnchenfilet, Chorizo, Paprika, Olivenöl, Paprikapulver', false, false, true, 6, true),
('tp007', 'Hähnchen Filet mit Brandy Sauce', 'Edle Hähnchenzubereitung', 'Gebratene Hähnchenfilets in einer edlen Brandy-Rahm-Sauce mit Pilzen.', '7,20', 'Hähnchen', 'Milch', 'Hähnchenfilet, Brandy, Sahne, Champignons, Zwiebeln, Kräuter', false, false, true, 7, true),

-- 6. Tapas de Carne
('tc001', 'Dátiles con Bacon', 'Datteln im Speckmantel', 'Entkernte Datteln gefüllt mit Mandeln, umhüllt von knusprigem Bacon und karamellisiert.', '6,90', 'Fleisch', 'Schalenfrüchte', 'Datteln, Mandeln, Bacon, Honig', false, false, true, 1, true),
('tc002', 'Albondigas a la Casera', 'Hackbällchen mit Tomatensauce', 'Hausgemachte Hackbällchen nach Großmutters Rezept in würziger Tomatensauce.', '6,90', 'Fleisch', 'Glutenhaltiges Getreide, Milch', 'Rinderhack, Schweinehack, Semmelbrösel, Eier, Tomaten, Zwiebeln', false, false, false, 2, true),
('tc003', 'Pincho de Cerdo', 'Schweinespieß scharf', 'Marinierte Schweinefleischstücke am Spieß gegrillt mit scharfen Gewürzen.', '7,90', 'Fleisch', '', 'Schweinefilet, Chili, Paprika, Knoblauch, Olivenöl, Gewürze', false, false, true, 3, true),
('tc004', 'Pincho de Cordero', 'Lammspieß scharf', 'Zarte Lammfleischstücke mariniert mit orientalischen Gewürzen und Kräutern.', '8,90', 'Fleisch', '', 'Lammfilet, Rosmarin, Thymian, Knoblauch, Olivenöl, Harissa', false, false, true, 4, true),
('tc005', 'Chuletas de Cordero', '2 Lammkoteletts', 'Zwei zarte Lammkoteletts gegrillt mit Rosmarin und Knoblauch, serviert mit Ratatouille.', '9,90', 'Fleisch', '', 'Lammkoteletts, Rosmarin, Knoblauch, Olivenöl, Gemüse', false, false, true, 5, true),
('tc006', 'Rollitos de Serrano con Higo', 'Feigen/Serrano, Frischkäse', 'Feigenscheiben mit Frischkäse, umhüllt von Serrano-Schinken und leicht gratiniert.', '9,90', 'Fleisch', 'Milch', 'Feigen, Serrano-Schinken, Frischkäse, Honig', false, false, true, 6, true),
('tc007', 'Queso de Cabra con Bacon', 'Ziegenkäse/Speck', 'Warmer Ziegenkäse umhüllt von knusprigem Bacon mit Honig und Walnüssen.', '7,90', 'Fleisch', 'Milch, Schalenfrüchte', 'Ziegenkäse, Bacon, Honig, Walnüsse', false, false, true, 7, true),
('tc008', 'Chorizo al Diablo', 'In Rotweinsauce', 'Pikante Chorizo geschmort in Rotweinsauce mit Zwiebeln und spanischen Gewürzen.', '7,90', 'Fleisch', '', 'Chorizo, Rotwein, Zwiebeln, Knoblauch, Paprika, Lorbeer', false, false, true, 8, true),
('tc009', 'Medallions de Carne', 'Rinderfilet, Pilz-Ragout', 'Zarte Rinderfilet-Medallions mit cremigem Pilz-Ragout und Kräutern der Provence.', '9,90', 'Fleisch', 'Milch', 'Rinderfilet, Champignons, Sahne, Kräuter, Schalotten', false, false, true, 9, true),
('tc010', 'Mit Käse gefüllte Champignons', 'Bacon, Kräuter', 'Große Champignons gefüllt mit Käse, Bacon und frischen Kräutern, überbacken.', '8,90', 'Fleisch', 'Milch, Glutenhaltiges Getreide', 'Champignons, Käse, Bacon, Petersilie, Semmelbrösel', false, false, false, 10, true),
('tc011', 'Schweinefilet mit Cherry Tomaten', 'Mango-Honig', 'Schweinefilet-Medaillons mit Cherry-Tomaten in exotischer Mango-Honig-Glasur.', '9,50', 'Fleisch', '', 'Schweinefilet, Cherry-Tomaten, Mango, Honig, Ingwer', false, false, true, 11, true),
('tc012', 'Schweinefilet', 'Spinat, Pilze, Cremefraiche', 'Schweinefilet-Medaillons auf Spinat-Pilz-Bett mit Crème fraîche-Sauce.', '9,50', 'Fleisch', 'Milch', 'Schweinefilet, Spinat, Champignons, Crème fraîche, Schalotten', false, false, true, 12, true),
('tc013', 'Chorizo a la Plancha', 'Gegrillt', 'Gegrillte Chorizo-Scheiben mit karamellisierten Zwiebeln und Paprika.', '7,90', 'Fleisch', '', 'Chorizo, Zwiebeln, Paprika, Olivenöl, Knoblauch', false, false, true, 13, true),
('tc014', 'Lammfilet', 'Mit Pfeffersauce', 'Rosa gebratenes Lammfilet mit cremiger grüner Pfeffersauce und Kräutern.', '9,90', 'Fleisch', 'Milch', 'Lammfilet, grüner Pfeffer, Sahne, Cognac, Kräuter', false, false, true, 14, true),
('tc015', 'Spareribs mit BBQ-Sauce', 'Amerikanische Art', 'Zarte Spareribs mit hausgemachter BBQ-Sauce, langsam gegart und karamellisiert.', '9,90', 'Fleisch', '', 'Spareribs, BBQ-Sauce, Honig, Gewürze, Zwiebeln', false, false, true, 15, true),
('tc016', 'Chicken Wings', 'Mit süßer Chillisauce', 'Knusprige Chicken Wings mit süß-scharfer Chili-Sauce und Sesam.', '9,90', 'Fleisch', 'Sesam', 'Chicken Wings, Chili, Honig, Sojasauce, Sesam, Ingwer', false, false, true, 16, true);