USE jimmys_tapas_bar;

-- 7. Tapas de Pescado
INSERT INTO menu_items (id, name, description, detailed_description, price, category, allergens, ingredients, vegan, vegetarian, glutenfree, order_index, is_active) VALUES
('tf001', 'Boquerones Fritos', 'Frittierte Sardellen', 'Kleine frittierte Sardellen in leichtem Teigmantel, serviert mit Zitrone und Aioli.', '7,50', 'Fisch', 'Fisch, Glutenhaltiges Getreide', 'Sardellen, Mehl, Olivenöl, Zitrone, Aioli', false, false, false, 1, true),
('tf002', 'Calamares a la Plancha', 'Gegrillt', 'Zarte Tintenfischringe vom Grill mit Knoblauch, Petersilie und Olivenöl.', '8,90', 'Fisch', 'Weichtiere', 'Calamares, Knoblauch, Petersilie, Olivenöl, Zitrone', false, false, true, 2, true),
('tf003', 'Calamares a la Romana', 'Frittiert mit Aioli', 'Klassisch frittierte Calamares-Ringe in knusprigem Teigmantel mit hausgemachter Aioli.', '7,50', 'Fisch', 'Weichtiere, Glutenhaltiges Getreide, Eier', 'Calamares, Mehl, Eier, Olivenöl, Aioli', false, false, false, 3, true),
('tf004', 'Salmon con Espinaca', 'Lachsfilet auf Spinat', 'Gebratenes Lachsfilet auf einem Bett aus frischem Spinat mit Knoblauch und Sahne.', '9,90', 'Fisch', 'Fisch, Milch', 'Lachsfilet, Spinat, Knoblauch, Sahne, Olivenöl', false, false, true, 4, true),
('tf005', 'Gambas a la Plancha', 'Gegrillte Tiger-Garnelen, Gemüse', 'Große Tiger-Garnelen vom Grill mit mediterranem Gemüse und Kräutern.', '9,90', 'Fisch', 'Schalentiere', 'Tiger-Garnelen, Zucchini, Paprika, Tomaten, Kräuter', false, false, true, 5, true),
('tf006', 'Garnelen-Dattel-Spieß', 'Speckmantel, Honig-Senf', 'Garnelen und Datteln am Spieß, umhüllt von Bacon, mit süßer Honig-Senf-Glasur.', '9,90', 'Fisch', 'Schalentiere', 'Garnelen, Datteln, Bacon, Honig, Senf', false, false, true, 6, true),
('tf007', 'Gambas al Ajillo', 'Knoblauch-Olivenöl', 'Klassische spanische Garnelen in viel Knoblauch und Olivenöl mit Chili und Petersilie.', '9,90', 'Fisch', 'Schalentiere', 'Garnelen, Knoblauch, Olivenöl, Chili, Petersilie', false, false, true, 7, true),
('tf008', 'Muslitos de Mar', 'Krebsfleischbällchen', 'Hausgemachte Bällchen aus Krebsfleisch mit Kräutern und Gewürzen, frittiert.', '6,90', 'Fisch', 'Schalentiere, Glutenhaltiges Getreide', 'Krebsfleisch, Semmelbrösel, Eier, Kräuter, Gewürze', false, false, false, 8, true),
('tf009', 'Gegrillter Oktopus', 'Kichererbsen, Gemüse', 'Zarter gegrillter Oktopus auf warmem Kichererbsen-Salat mit Gemüse.', '9,90', 'Fisch', 'Weichtiere', 'Oktopus, Kichererbsen, Paprika, Zwiebeln, Olivenöl', false, false, true, 9, true),
('tf010', 'Jacobsmuscheln', 'Spinat, Cherry Tomaten', 'Gebratene Jacobsmuscheln auf Spinat mit Cherry-Tomaten und Knoblauch.', '9,90', 'Fisch', 'Weichtiere', 'Jacobsmuscheln, Spinat, Cherry-Tomaten, Knoblauch, Butter', false, false, true, 10, true),
('tf011', 'Gambas PIL PIL', 'Scharfe Tomatensauce', 'Garnelen in pikanter Tomatensauce mit Chili, Knoblauch und spanischen Gewürzen.', '9,90', 'Fisch', 'Schalentiere', 'Garnelen, Tomaten, Chili, Knoblauch, Paprika, Zwiebeln', false, false, true, 11, true),
('tf012', 'Empanadas', 'Thunfisch, gefüllter Teig', 'Traditionelle spanische Teigtaschen gefüllt mit würzigem Thunfisch und Gemüse.', '6,90', 'Fisch', 'Fisch, Glutenhaltiges Getreide, Eier', 'Blätterteig, Thunfisch, Zwiebeln, Paprika, Eier', false, false, false, 12, true),
('tf013', 'Pfahlmuscheln', 'Nach spanischer Art', 'Pfahlmuscheln in Weißwein-Sud mit Knoblauch, Petersilie und spanischem Sofrito.', '8,90', 'Fisch', 'Weichtiere', 'Pfahlmuscheln, Weißwein, Knoblauch, Petersilie, Tomaten', false, false, true, 13, true),
('tf014', 'Pulpo al Ajillo', 'Oktopus, Knoblauch', 'Oktopus-Stücke in viel Knoblauch und Olivenöl mit Paprika und Petersilie gebraten.', '9,90', 'Fisch', 'Weichtiere', 'Oktopus, Knoblauch, Olivenöl, Paprika, Petersilie', false, false, true, 14, true),
('tf015', 'Zander Filet', 'Bacon, Knoblauch-Sahnesauce', 'Gebratenes Zanderfilet mit Bacon und cremiger Knoblauch-Sahnesauce.', '9,90', 'Fisch', 'Fisch, Milch', 'Zanderfilet, Bacon, Knoblauch, Sahne, Kräuter', false, false, true, 15, true),
('tf016', 'Tiger Garnelen', 'Tomaten, Paprika, Knoblauch, Oliven', 'Tiger-Garnelen in mediterraner Sauce mit Tomaten, Paprika und Oliven.', '9,90', 'Fisch', 'Schalentiere', 'Tiger-Garnelen, Tomaten, Paprika, Knoblauch, Oliven', false, false, true, 16, true),
('tf017', 'Brocheta de Gambas', 'Gambas Spieß', 'Garnelen-Spieß mariniert mit Kräutern und Gewürzen, gegrillt und glasiert.', '8,90', 'Fisch', 'Schalentiere', 'Garnelen, Olivenöl, Kräuter, Knoblauch, Zitrone', false, false, true, 17, true),
('tf018', 'Boqueron en Tempura', 'Panierte Sardellen', 'Sardellen in leichtem Tempura-Teig frittiert, serviert mit würziger Dip-Sauce.', '7,50', 'Fisch', 'Fisch, Glutenhaltiges Getreide', 'Sardellen, Tempura-Mehl, Eiswasser, Dip-Sauce', false, false, false, 18, true),
('tf019', 'Chipirones Fritos con Aioli', 'Baby-Calamares frittiert', 'Kleine frittierte Baby-Calamares mit hausgemachter Aioli und Zitrone.', '8,90', 'Fisch', 'Weichtiere, Eier', 'Baby-Calamares, Mehl, Olivenöl, Aioli, Zitrone', false, false, false, 19, true),

-- 8. Kroketten
('k001', 'Croquetas de Bacalao', 'Stockfisch', 'Traditionelle spanische Kroketten mit gesalzenem Stockfisch und Béchamel-Sauce.', '5,90', 'Kroketten', 'Fisch, Glutenhaltiges Getreide, Milch', 'Stockfisch, Mehl, Milch, Butter, Semmelbrösel', false, false, false, 1, true),
('k002', 'Croquetas de Queso', 'Fetakäse', 'Cremige Kroketten gefüllt mit würzigem Feta-Käse und mediterranen Kräutern.', '5,90', 'Kroketten', 'Milch, Glutenhaltiges Getreide', 'Feta-Käse, Mehl, Milch, Butter, Kräuter, Semmelbrösel', false, true, false, 2, true),
('k003', 'Croquetas de Almendras', 'Mandeln', 'Besondere Kroketten mit gerösteten Mandeln und einem Hauch von Sherry.', '6,50', 'Kroketten', 'Schalenfrüchte, Glutenhaltiges Getreide, Milch', 'Mandeln, Mehl, Milch, Butter, Sherry, Semmelbrösel', false, true, false, 3, true),
('k004', 'Croquetas de Jamón', 'Serrano Schinken', 'Klassische Schinken-Kroketten mit Serrano-Schinken und würziger Béchamel.', '5,90', 'Kroketten', 'Glutenhaltiges Getreide, Milch', 'Serrano-Schinken, Mehl, Milch, Butter, Semmelbrösel', false, false, false, 4, true),
('k005', 'Croquetas de Patata', 'Kartoffel', 'Vegetarische Kartoffel-Kroketten mit Kräutern und spanischen Gewürzen.', '5,50', 'Kroketten', 'Glutenhaltiges Getreide, Milch', 'Kartoffeln, Mehl, Milch, Butter, Kräuter, Semmelbrösel', false, true, false, 5, true),

-- 9. Pasta
('pa001', 'Spaghetti Aglio e Olio', 'Mit Knoblauch und Olivenöl', 'Klassische italienische Pasta mit Knoblauch, Olivenöl, Chili und Petersilie.', '12,90', 'Pasta', 'Glutenhaltiges Getreide', 'Spaghetti, Knoblauch, Olivenöl, Chili, Petersilie', true, true, false, 1, true),
('pa002', 'Spaghetti Bolognese', 'Mit Fleischsauce', 'Spaghetti mit hausgemachter Bolognese-Sauce aus Rind- und Schweinefleisch.', '14,90', 'Pasta', 'Glutenhaltiges Getreide', 'Spaghetti, Rinderhack, Schweinehack, Tomaten, Gemüse', false, false, false, 2, true),
('pa003', 'Pasta Brokkoli Gorgonzola', 'Cremige Käsesauce', 'Pasta mit Brokkoli in cremiger Gorgonzola-Sahne-Sauce mit Walnüssen.', '14,90', 'Pasta', 'Glutenhaltiges Getreide, Milch, Schalenfrüchte', 'Pasta, Brokkoli, Gorgonzola, Sahne, Walnüsse', false, true, false, 3, true),
('pa004', 'Pasta Verdura', 'Mit Gemüse', 'Pasta mit frischem saisonalem Gemüse in Tomaten-Kräuter-Sauce.', '14,90', 'Pasta', 'Glutenhaltiges Getreide', 'Pasta, Zucchini, Paprika, Auberginen, Tomaten, Kräuter', true, true, false, 4, true),
('pa005', 'Pasta Garnelen', 'Mit Garnelen', 'Pasta mit Tiger-Garnelen in Knoblauch-Weißwein-Sauce mit Cherry-Tomaten.', '16,90', 'Pasta', 'Glutenhaltiges Getreide, Schalentiere', 'Pasta, Garnelen, Knoblauch, Weißwein, Cherry-Tomaten', false, false, false, 5, true),

-- 10. Pizza
('pz001', 'Pizza Margharita', 'Tomaten, Mozzarella, Basilikum', 'Klassische Pizza mit Tomatensauce, Mozzarella und frischem Basilikum.', '9,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Basilikum', false, true, false, 1, true),
('pz002', 'Pizza Schinken', 'Mit Schinken', 'Pizza mit Tomatensauce, Mozzarella und italienischem Schinken.', '12,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Schinken', false, false, false, 2, true),
('pz003', 'Pizza Funghi', 'Mit Champignons', 'Pizza mit Tomatensauce, Mozzarella und frischen Champignons.', '12,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Champignons', false, true, false, 3, true),
('pz004', 'Pizza Tonno', 'Mit Thunfisch', 'Pizza mit Tomatensauce, Mozzarella, Thunfisch und roten Zwiebeln.', '13,90', 'Pizza', 'Glutenhaltiges Getreide, Milch, Fisch', 'Pizzateig, Tomatensauce, Mozzarella, Thunfisch, Zwiebeln', false, false, false, 4, true),
('pz005', 'Pizza Hawaii', 'Mit Ananas und Schinken', 'Pizza mit Tomatensauce, Mozzarella, Schinken und Ananas.', '13,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Schinken, Ananas', false, false, false, 5, true),
('pz006', 'Pizza Verdura', 'Mit Gemüse', 'Pizza mit Tomatensauce, Mozzarella und gegrilltem Gemüse der Saison.', '13,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Gemüse', false, true, false, 6, true),
('pz007', 'Pizza Salami', 'Mit Salami', 'Pizza mit Tomatensauce, Mozzarella und würziger italienischer Salami.', '12,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Salami', false, false, false, 7, true),
('pz008', 'Pizza Garnelen', 'Mit Garnelen', 'Pizza mit Tomatensauce, Mozzarella, Garnelen und Knoblauch.', '15,90', 'Pizza', 'Glutenhaltiges Getreide, Milch, Schalentiere', 'Pizzateig, Tomatensauce, Mozzarella, Garnelen, Knoblauch', false, false, false, 8, true),
('pz009', 'Pizza Bolognese', 'Mit Fleischsauce', 'Pizza mit Bolognese-Sauce, Mozzarella und frischen Kräutern.', '13,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Bolognese-Sauce, Mozzarella, Kräuter', false, false, false, 9, true),
('pz010', 'Jimmy\'s Special Pizza', 'Hausspezialität', 'Pizza mit Tomatensauce, Mozzarella, Serrano-Schinken, Rucola und Parmesan.', '13,90', 'Pizza', 'Glutenhaltiges Getreide, Milch', 'Pizzateig, Tomatensauce, Mozzarella, Serrano, Rucola, Parmesan', false, false, false, 10, true);